name: Longer Days
main: com.lith.longerdays.Plugin

version: 0.0.1
api-version: 1.20

description: A MineCraft plugin for Longer Days
author: Lith
website: https://github.com/ImLith/mc-longer-days

depend: []
softdepend: []
